server.port=${PORT:8080}

spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.cachecontrol.no-cache=true

spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=TravelPlannerSuperSecretJwtKey2024ThatIsAtLeast256BitsLong!!
jwt.expiration=86400000
