CREATE TABLE IF NOT EXISTS users (
    id varchar(255) NOT NULL,
    username varchar(255),
    email varchar(255),
    password varchar(255),
    created_at varchar(255),
    language varchar(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS countries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    country varchar(255),
    currency_code varchar(255),
    currency_name_en varchar(255),
    currency_name_pl varchar(255),
    CONSTRAINT countries_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS currencies (
    code varchar(255) NOT NULL,
    name varchar(255),
    name_pl varchar(255),
    name_es varchar(255),
    rate double precision NOT NULL,
    effective_date varchar(255),
    CONSTRAINT currencies_pkey PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS trips (
    id varchar(255) NOT NULL,
    name varchar(255),
    destination varchar(255),
    country varchar(255),
    start_date varchar(255),
    end_date varchar(255),
    budget double precision NOT NULL,
    currency varchar(255),
    notes varchar(255),
    destination_notes varchar(255),
    weather varchar(255),
    destination_currency varchar(255),
    currency_code varchar(255),
    tips varchar(255),
    created_at varchar(255),
    user_id varchar(255),
    CONSTRAINT trips_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS itinerary_items (
    id varchar(255) NOT NULL,
    "day" integer NOT NULL,
    "time" varchar(255),
    title varchar(255),
    description varchar(255),
    trip_id varchar(255),
    CONSTRAINT itinerary_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS expenses (
    id varchar(255) NOT NULL,
    category varchar(255),
    amount double precision NOT NULL,
    description varchar(255),
    added_at varchar(255),
    rate_to_pln double precision DEFAULT 1.0,
    trip_id varchar(255),
    CONSTRAINT expenses_pkey PRIMARY KEY (id)
);

ALTER TABLE trips
    ADD CONSTRAINT fk_trips_user
    FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE itinerary_items
    ADD CONSTRAINT fk_itinerary_items_trip
    FOREIGN KEY (trip_id) REFERENCES trips (id);

ALTER TABLE expenses
    ADD CONSTRAINT fk_expenses_trip
    FOREIGN KEY (trip_id) REFERENCES trips (id);
